name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: hansi2007
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=%23ff69b4&color_dots=%23f0f0f0,%23ffc0cb,%23ff91a4,%23ff69b4,%23ff1493

      - name: Push Snake to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
